### ISSUE TITLE
Pre-processing data for BERT

### ISSUE THREAD

**Issue by pachiko** [chrischute/squad#1]
Hi,

What is the quickest way to edit the data pre-processing code so that we can load BERT models from the huggingface repo? AFAIK, BERT receives the question and context tokens as one sequence, with SEP tokens in between and the end. There's also a CLS token at the head of each sequence/example. But for the BIDAF model that comes with this starter code, it receives question and context as separate tensors...

Thanks.

**Comment by chrischute** [comment]
I would recommend using the Huggingface repo as your starting point rather than this repo (see especially [run_squad.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py)). They have all the pre-processing already set up for BERT, and it would be easier to move code from this repo to that one, rather than the other way around.
